# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jason Cui
tagline:             My personal site.
url:                 http://jasoncui.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jason Cui
  url:               https://twitter.com/jasonscui
  email:             jasoncui@college.harvard.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# List of pages for the header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Contact: '/contact'
