# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jason Cui
tagline:          'A Jekyll theme'
description:      'Student <a href="http://www.harvard.edu" target="_blank">@Harvard</a> and product <a href="https://www.uber.com/" target="_blank">@Uber</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jason Cui'
  url:            https://twitter.com/JasonSCui

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
